### ISSUE TITLE
Fails to build with Python 3.10: undefined symbol: PyObject_AsWriteBuffer

### ISSUE THREAD

**Issue by audreytoskin** [jwilk/python-djvulibre#13]
I package python-djvulibre for the Linux distribution Fedora. There we're planning a future release, Fedora 35, which will ship with the upcoming release of Python 3.10, and we're testing packages early to try to make the transition as smooth as possible. And for those tests, python-djvulibre fails to build against Python 3.10.0a.

...That is of course still a prerelease, so it's not a serious problem _yet_, but something to keep in mind for upcoming development...

From the upstream changelog here -- https://docs.python.org/3.10/whatsnew/changelog.html#id16 --

> bpo-41103: `PyObject_AsCharBuffer()`, `PyObject_AsReadBuffer()`, `PyObject_CheckReadBuffer()`, and `PyObject_AsWriteBuffer()` are removed. Please migrate to new buffer protocol; `PyObject_GetBuffer()` and `PyBuffer_Release()`.

**Comment by jwilk** [comment]
Downstream bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1897558

**Comment by jwilk** [comment]
Fixed in 3a61d30c38b0abec4e4ef22f1c63b1003ba2d35f.

If all goes well, I'll make a new release in a few days.

**Comment by jwilk** [comment]
Fixed in [0.8.6](https://pypi.org/project/python-djvulibre/0.8.6/).
