### ISSUE TITLE
test_thumbnails fail

### ISSUE THREAD

**Issue by aekoroglu** [jwilk/python-djvulibre#22]
Hello, I'm updating python-djvulibre to 0.8.7 for Fedora but pytest fails at test_thumbnails on rawhide and f36 only in i686 architecture (https://koji.fedoraproject.org/koji/taskinfo?taskID=89694113).
Do you have any idea about the problem ?

-- rawhide (djvulibre 3.5.28, gcc 12.1.1 20220628, cython 0.29.30)
============================= test session starts ==============================
platform linux -- Python 3.11.0b4, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3

test_thumbnails.test
AssertionError: b'\x83\xcc\xa7\x7f\x9e\x7f\x9e\x86\x7f\xc7\x7f\xc7\xd6\xc8\x82' != b'\xff\xeb\xa7\xf2\xff\xff\xbf\x86\xbe\xff\xff\xe7\xd6\xe7\xff'

-- f36 (djvulibre 3.5.28, gcc 12.1.1 20220507, cython 0.29.26)
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3

test_thumbnails.test
AssertionError: b'\x83\xcc\xa7\x7f\x9e\x7f\x9e\x86\x7f\xc7\x7f\xc7\xd6\xc8\x82' != b'\xff\xeb\xa7\xf2\xff\xff\xbf\x86\xbe\xff\xff\xe7\xd6\xe7\xff'

-- f35 - success (djvulibre 3.5.27, gcc 11.3.1 20220421, cython 0.29.24)
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3

**Comment by jwilk** [comment]
Thanks for the bug report.

I couldn't reproduce in Debian unstable, but I did reproduce it in Fedora 36.

Very odd. I have no idea what's going on.

**Comment by jwilk** [comment]
I've managed to reproduce the bug on a Debian system by upgrading libc6 to 2.34 (from experimental), and then replacing `libdjvulibre.so.21` with the one from Fedora.

(OTOH, rebuilding the Debian DjVuLibre package against GCC 12 and glibc 2.34 and installing that does not make the bug appear.)

**Comment by aekoroglu** [comment]
Couple of weeks later we were able to compile the code, thank you.
https://bodhi.fedoraproject.org/updates/FEDORA-2022-1a97e46b73
